name: Sync files to another repo

on:
  push:
    branches:
      - master

jobs:
  sync-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
      - name: Clone destination repo
        run: |
          mkdir /home/runner/work/destination-repo
          git clone https://x-access-token:${{ secrets.TARGET_REPO_TOKEN }}@github.com/hoyosK/workflow.git /home/runner/work/destination-repo
      - name: Copy files to destination repo
        run: |
          pwd
          cp -r /home/runner/work/workflow1/workflow1/* /home/runner/work/destination-repo
          
      - name: Commit and push changes
        run: |
          cd /home/runner/work/destination-repo
          git add .
          git commit -m "Sync from source repo" || echo "Nothing to commit"
          git push
